### ISSUE TITLE
Uncaught Error: cannot serialize type undefined to BSER

### ISSUE THREAD

**Issue by capoony** [lewisf/atom-smart-path-autocomplete#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-smart-path-autocomplete](https://github.com/lewisf/atom-smart-path-autocomplete) package 0.1.0

### Stack Trace

Uncaught Error: cannot serialize type undefined to BSER

```
At /Users/mkapun/.atom/packages/atom-smart-path-autocomplete/node_modules/bser/index.js:553

Error: cannot serialize type undefined to BSER
    at dump_any (/packages/atom-smart-path-autocomplete/node_modules/bser/index.js:553:13)
    at dump_any (/packages/atom-smart-path-autocomplete/node_modules/bser/index.js:517:11)
    at Object.dumpToBuffer (/packages/atom-smart-path-autocomplete/node_modules/bser/index.js:567:3)
    at Client.sendNextCommand (/packages/atom-smart-path-autocomplete/node_modules/fb-watchman/index.js:48:26)
    at /packages/atom-smart-path-autocomplete/node_modules/fb-watchman/index.js:114:12)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1169:10)
```

### Commands

```
     -0:14 application:new-file (input.hidden-input)
```

### Non-Core Packages

```
atom-smart-path-autocomplete 0.1.0 
autocomplete-awk 0.1.2 
autocomplete-bash-builtins 0.3.5 
autocomplete-python 1.14.0 
autocomplete-R 0.6.0 
drag-relative-path 1.1.3 
Hydrogen 2.8.0 
ide-bash 1.0.11 
ide-python 1.4.1 
kite 0.153.0 
platformio-ide-terminal 2.9.1 
python-debugger 0.2.0 
python-snippets 1.9.0 
script 3.18.1 
sync-settings 0.8.6 
```

**Comment by jaredmichaelwilliams** [comment]
anyone fix this?
